### ISSUE TITLE
How to reference ${env.WORKSPACE}?

### ISSUE THREAD

**Issue by chrisliu529** [jenkinsci/workflow-aggregator-plugin#4]
As it mentioned in pipeline dsl reference:
WORKSPACE variable is currently not available in pipeline script.

However, normally the first line in shell script of build step in a jenkins job setup is
```
cd ${WORKSPACE}
# then do something there..
```
Now I'm a bit confused about how to handle the use case above in pipeline script?

**Comment by jglick** [comment]
`pwd()` but please do not use the GH issue tracker. I will turn it off. Use StackOverflow, #jenkins, the user list, etc.
